refac: accomodate web deploy for peterpans too (#398)
Co-authored-by: ashesh11 <ashesh.bh@gmail.com>

diff --git a/.github/workflows/deploy_web.yml b/.github/workflows/deploy_web.yml
--- a/.github/workflows/deploy_web.yml
+++ b/.github/workflows/deploy_web.yml
@@ -15,6 +15,10 @@ on:
       github-branch-name:
         description: 'Github repo branch name for web.'
         required: true
+      platform:
+        description: 'Platform to deploy to (freelance or peterpans)'
+        required: true
+        default: 'freelance'
       environment:
         description: 'Environment to deploy to (staging or production)'
         required: true
@@ -22,9 +26,11 @@ on:
 
 env:
   S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
+  S3_BUCKET_NAME_PETERPANS: ${{ vars.S3_BUCKET_NAME_PETERPANS }}
   CLARITY_CODE_BLOCK : ${{ vars.CLARITY_CODE_BLOCK }}
   HELP_SCOUT_CODE_BLOCK: ${{ vars.HELP_SCOUT_CODE_BLOCK }}
   CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
+  PLATFORM: ${{ github.event.inputs.platform }}
 
 jobs:
   build:
@@ -32,10 +38,16 @@ jobs:
     environment: ${{ github.event.inputs.environment }}
 
     steps:
+      - name: Fail on Invalid Platform
+        if: ${{ github.event.inputs.platform != 'freelance' && github.event.inputs.platform != 'peterpans' }}
+        run: |
+          echo "Invalid platform: ${{ github.event.inputs.platform }}. Options are 'freelance' or 'peterpans'."
+          exit 1
+
       - name: Fail on Invalid Environment
         if: ${{ github.event.inputs.environment != 'staging' && github.event.inputs.environment != 'production' }}
         run: |
-          echo "Invalid environment: ${{ github.event.inputs.environment }}. Options are 'staging' or 'production."
+          echo "Invalid environment: ${{ github.event.inputs.environment }}. Options are 'staging' or 'production'."
           exit 1
 
       - name: Set up SSH for Deploy Key
@@ -51,7 +63,8 @@ jobs:
       - name: Setup index html
         run: |
           cd freelance-website
-          envsubst < public-freelance/index.tpl.html > public-freelance/index.html
+          export PLATFORM=${{ github.event.inputs.platform }}
+          envsubst < public-$PLATFORM/index.tpl.html > public-$PLATFORM/index.html
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
@@ -77,8 +90,17 @@ jobs:
           aws-region: ap-southeast-2
 
       - name: Remove all files from S3
-        run: aws s3 rm s3://$S3_BUCKET_NAME --recursive --region $AWS_REGION
+        run: |
+          if [ "${{ github.event.inputs.platform }}" = "freelance" ]; then
+            aws s3 rm s3://$S3_BUCKET_NAME --recursive --region $AWS_REGION
+          elif [ "${{ github.event.inputs.platform }}" = "peterpans" ]; then
+            aws s3 rm s3://$S3_BUCKET_NAME_PETERPANS --recursive --region $AWS_REGION
+          fi
 
       - name: Deploy Frontend to S3
         run: |
-          aws s3 sync freelance-website/build/ s3://$S3_BUCKET_NAME --delete --region $AWS_REGION
+          if [ "${{ github.event.inputs.platform }}" = "freelance" ]; then
+            aws s3 sync freelance-website/build/ s3://$S3_BUCKET_NAME --delete --region $AWS_REGION
+          elif [ "${{ github.event.inputs.platform }}" = "peterpans" ]; then
+            aws s3 sync freelance-website/build/ s3://$S3_BUCKET_NAME_PETERPANS --delete --region $AWS_REGION
+          fi
