refac: add cloudfront invalidation in actions (#310)
Co-authored-by: ashesh11 <ashesh.bh@gmail.com>

diff --git a/.github/workflows/deploy_api.yml b/.github/workflows/deploy_api.yml
--- a/.github/workflows/deploy_api.yml
+++ b/.github/workflows/deploy_api.yml
@@ -81,16 +81,20 @@ env:
       FIREBASE_PROJECT_ID: ${{vars.FIREBASE_PROJECT_ID}}
 
 jobs:
+  validate-environment:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail on Invalid Environment
+        if: ${{ github.event.inputs.environment != 'staging' && github.event.inputs.environment != 'production' }}
+        run: |
+          echo "Invalid environment: ${{ github.event.inputs.environment }}. Options are 'staging' or 'production."
+          exit 1
+  
   build:
     runs-on: ubuntu-latest
     environment: ${{ github.event.inputs.environment }}
-    
+    needs: validate-environment
     steps:
-    - name: Fail on Invalid Environment
-      if: ${{ github.event.inputs.environment != 'staging' && github.event.inputs.environment != 'production' }}
-      run: |
-        echo "Invalid environment: ${{ github.event.inputs.environment }}. Options are 'staging' or 'production."
-        exit 1
 
     - name: Checkout Code
       uses: actions/checkout@v3
