ci: allow deploying in prod (#150)
* feat: github action to handle different environments

* feat: add new db docker compose for production and update action accordingly

* feat: pass network name and ip's from variables

* fix

diff --git a/.github/workflows/deploy_api.yml b/.github/workflows/deploy_api.yml
--- a/.github/workflows/deploy_api.yml
+++ b/.github/workflows/deploy_api.yml
@@ -17,6 +17,10 @@ on:
       docker_hub_password:
         description: 'Password of Docker hub'
         required: true
+      environment:
+        description: 'Environment to deploy to (staging or production)'
+        required: true
+        default: 'staging'
 
 env:
       APP_NAME: ${{ vars.APP_NAME }}
@@ -25,6 +29,7 @@ env:
       APP_DEBUG: ${{ vars.APP_DEBUG }}
       APP_URL: ${{ vars.APP_URL }}
       APP_PORT: ${{ vars.APP_PORT }}
+      NETWORK_NAME: ${{vars.NETWORK_NAME}}
       API_IP_ADDRESS: ${{ vars.API_IP_ADDRESS }}
       DB_CONNECTION: ${{ vars.DB_CONNECTION }}
       DB_HOST: ${{ vars.DB_IP_ADDRESS }}
@@ -67,9 +72,15 @@ env:
 jobs:
   build:
     runs-on: ubuntu-latest
-    environment: staging
+    environment: ${{ github.event.inputs.environment }}
     
     steps:
+    - name: Fail on Invalid Environment
+      if: ${{ github.event.inputs.environment != 'staging' && github.event.inputs.environment != 'production' }}
+      run: |
+        echo "Invalid environment: ${{ github.event.inputs.environment }}. Options are 'staging' or 'production."
+        exit 1
+
     - name: Checkout Code
       uses: actions/checkout@v3
 
@@ -106,7 +117,7 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     needs: build
-    environment: staging
+    environment: ${{ github.event.inputs.environment }}
 
     steps:
     - name: Checkout Code
diff --git a/.github/workflows/deploy_db.yml b/.github/workflows/deploy_db.yml
--- a/.github/workflows/deploy_db.yml
+++ b/.github/workflows/deploy_db.yml
@@ -2,6 +2,11 @@ name: Freelance travel db deployment
 
 on:
   workflow_dispatch:
+    inputs:
+      environment:
+        description: 'Environment to deploy to (staging or production)'
+        required: true
+        default: 'staging'
 
 env:
   DB_HOST: ${{ vars.DB_HOST }}
@@ -13,13 +18,21 @@ env:
   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
   EC2_HOST: ${{ secrets.EC2_HOST }}
   EC2_USER: ${{ secrets.EC2_USER }}
+  NETWORK_NAME: ${{ vars.NETWORK_NAME }}
+  DB_IP_ADDRESS: ${{ vars.DB_IP_ADDRESS }}
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    environment: staging
+    environment: ${{ github.event.inputs.environment }}
 
     steps:
+    - name: Fail on Invalid Environment
+      if: ${{ github.event.inputs.environment != 'staging' && github.event.inputs.environment != 'production' }}
+      run: |
+        echo "Invalid environment: ${{ github.event.inputs.environment }}. Options are 'staging' or 'production."
+        exit 1
+
     - name: Checkout Code
       uses: actions/checkout@v3
       
@@ -36,8 +49,11 @@ jobs:
         # Add EC2's IP address to known hosts to avoid host key verification issues
         ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
 
+        # Select the appropriate template based on the environment
+        TEMPLATE_FILE="deployment/db-compose-${{ github.event.inputs.environment }}.template.txt"
+
         # Create and Copy docker compose file to EC2 instance
-        envsubst < deployment/db-compose.template.txt > db-compose.yml
+        envsubst < $TEMPLATE_FILE > db-compose.yml
         scp -i ec2_key.pem db-compose.yml $EC2_USER@$EC2_HOST:~/deploy/db/db-compose.yml
 
         # SSH into the EC2 instance and pull the new Docker image, then restart the services using Docker Compose
diff --git a/.github/workflows/deploy_web.yml b/.github/workflows/deploy_web.yml
--- a/.github/workflows/deploy_web.yml
+++ b/.github/workflows/deploy_web.yml
@@ -15,6 +15,10 @@ on:
       github-branch-name:
         description: 'Github repo branch name for web.'
         required: true
+      environment:
+        description: 'Environment to deploy to (staging or production)'
+        required: true
+        default: 'staging'
 
 env:
   S3_BUCKET_NAME: apptest-freelance-travel-com
@@ -23,8 +27,15 @@ env:
 jobs:
   build:
     runs-on: ubuntu-latest
+    environment: ${{ github.event.inputs.environment }}
 
     steps:
+      - name: Fail on Invalid Environment
+        if: ${{ github.event.inputs.environment != 'staging' && github.event.inputs.environment != 'production' }}
+        run: |
+          echo "Invalid environment: ${{ github.event.inputs.environment }}. Options are 'staging' or 'production."
+          exit 1
+
       - name: Set up SSH for Deploy Key
         run: |
           mkdir ~/.ssh
@@ -50,7 +61,7 @@ jobs:
         working-directory: freelance-website
 
       - name: Build Frontend
-        run: npm run build:staging
+        run: npm run build:${{ github.event.inputs.environment }}
         working-directory: freelance-website
       
       # Configure AWS credentials
diff --git a/.github/workflows/setup_network.yml b/.github/workflows/setup_network.yml
--- a/.github/workflows/setup_network.yml
+++ b/.github/workflows/setup_network.yml
@@ -3,28 +3,30 @@ name: Freelance travel network setup
 on:
   workflow_dispatch:
     inputs:
-        network_subnet:
-            description: 'Docker network subnet'
-            required: true
-        api_ip_address:
-            description: 'IP address for api'
-            required: true
-        db_ip_address:
-            description: 'IP address for db'
-            required: true
-
+        environment:
+          description: 'Environment to deploy to (staging or production)'
+          required: true
+          default: 'staging'
+          
 env:
     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
     EC2_HOST: ${{ secrets.EC2_HOST }}
     EC2_USER: ${{ secrets.EC2_USER }}
+    NETWORK_NAME: ${{ vars.NETWORK_NAME }}
+    NETWORK_SUBNET: ${{ vars.NETWORK_SUBNET }}
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    environment: staging
+    environment: ${{ github.event.inputs.environment }}
 
     steps:
-      
+    - name: Fail on Invalid Environment
+      if: ${{ github.event.inputs.environment != 'staging' && github.event.inputs.environment != 'production' }}
+      run: |
+        echo "Invalid environment: ${{ github.event.inputs.environment }}. Options are 'staging' or 'production."
+        exit 1
+
     - name: Deploy db to EC2 instance
       run: |
         # Write the RSA private key to a temporary file
@@ -42,6 +44,6 @@ jobs:
         echo 'Getting into EC2 server'
         ssh -i ec2_key.pem $EC2_USER@$EC2_HOST << EOF
             # Create a Docker network if it doesn't exist
-            docker network create --driver=bridge --subnet=${{ github.action.inputs.network_subnet }}/16 ft-network
+            docker network create --driver=bridge --subnet=$NETWORK_SUBNET $NETWORK_NAME
 
         EOF
